sudo: false

env:
  global:
    - PYTHONUNBUFFERED=yes
    - secure: "TyC3F7uBmd4iWLpUyhIDkpRfbhPUmRqFeFhr12VSHfzODQfeLBqB9hHMhhjVLlk1gsQwIXzNDY2X82U83d4gG0X+SEPDUpTimuWc/GJoJLQL4+uyfpS8seQWnxa7ZXkZrUdKb2owHtx+0ESzZwfOg+pd0OxoMenK9bcGo3hZtkk="

addons:
  apt:
    packages:
      - zsh
      - csh
      - tcsh
      - posh


matrix:
  include:
    - python: '2.7'
      os: linux
      language: python
    - python: '3.4'
      os: linux
      language: python
    - python: '3.5'
      os: linux
      language: python
    - python: '3.5'
      env: FLAKE8=true
      os: linux
      language: python
    - os: osx
      env: PYTHON_VERSION=3.5
    - python: '3.5'
      env: CONDA_BUILD=2.0.1
      os: linux
      language: python

install:
  - echo "START INSTALLING"
  - which -a python
  - env | sort
  - source ./utils/travis-run-install.sh
  - echo "DONE INSTALLING"

# CSH has issues when variables get too long
# A common error that may occur would be a "Word too long" error and is probably related to the PATH variable
# Here we use "envvar_cleanup.sh" to remove duplicates from the path variable before trying to run the tests
script:
  - echo "START RUNNING"
  - which -a python
  - env | sort
  - export PATH=$(./shell/envvar_cleanup.sh "$PATH" -d)
  - source ./utils/travis-run-script.sh
  - echo "DONE RUNNING"

sudo: false

after_success:
  - pip install codecov coveralls scrutinizer-ocular
  - codecov --env PY_VERSION
  - coveralls || true
  - ocular || true
