sudo: false
language: generic

env:
  global:
    - PYTHONUNBUFFERED=yes
    - secure: "TyC3F7uBmd4iWLpUyhIDkpRfbhPUmRqFeFhr12VSHfzODQfeLBqB9hHMhhjVLlk1gsQwIXzNDY2X82U83d4gG0X+SEPDUpTimuWc/GJoJLQL4+uyfpS8seQWnxa7ZXkZrUdKb2owHtx+0ESzZwfOg+pd0OxoMenK9bcGo3hZtkk="

addons:
  apt:
    packages:
      - zsh

matrix:
  include:
    - env: PYTHON_VERSION=3.6
      os: linux
    - env: PYTHON_VERSION=3.4
      os: linux
    - env: PYTHON_VERSION=2.7
      os: linux
    - env: PYTHON_VERSION=3.6 FLAKE8=true
      os: linux
    - env: PYTHON_VERSION=3.6
      os: osx
    - env: PYTHON_VERSION=3.6 CONDA_BUILD=2.1.3
      os: linux
    - env: PYTHON_VERSION=3.6 SUDO=true
      os: linux
      sudo: true
  allow_failures:
    - env: PYTHON_VERSION=3.6 SUDO=true

install:
  - which -a python
  - env | sort
  - source ./utils/travis-run-install.sh

script:
  - source ./utils/travis-run-script.sh

sudo: false
