env:
  global:
    - PYTHONUNBUFFERED=yes
    - secure: "TyC3F7uBmd4iWLpUyhIDkpRfbhPUmRqFeFhr12VSHfzODQfeLBqB9hHMhhjVLlk1gsQwIXzNDY2X82U83d4gG0X+SEPDUpTimuWc/GJoJLQL4+uyfpS8seQWnxa7ZXkZrUdKb2owHtx+0ESzZwfOg+pd0OxoMenK9bcGo3hZtkk="

addons:
  apt:
    packages:
      - zsh

matrix:
  include:
    - env: PYTHON_VERSION=3.6
      sudo: true
      language: generic
      os: linux
    - env: PYTHON_VERSION=3.4
      sudo: false
      language: generic
      os: linux
    - env: PYTHON_VERSION=2.7
      sudo: false
      language: generic
      os: linux
    - env: FLAKE8=true
      sudo: false
      language: python
      python: '3.5'
      os: linux
    - env: PYTHON_VERSION=3.6
      sudo: false
      language: generic
      os: osx
    - env: PYTHON_VERSION=3.6 CONDA_BUILD=2.1.3
      sudo: false
      language: generic
      os: linux
  allow_failures:
    - os: osx

install:
  - which -a python
  - env | sort
  - source ./utils/travis-run-install.sh

script:
  - source ./utils/travis-run-script.sh
