image: Visual Studio 2017

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\appveyor\\run_with_env.cmd"
  COVERALLS_REPO_TOKEN:
    secure: ZaE7K9EHorv40AjYhSuWtQeRAsMN1+QqPf7u8rOlvEY50kdaHj87Mh5GIDZgJBzj

  matrix:
     - PYTHON: "C:\\Python36_64"
       PYTHON_VERSION: "3.6"
       PYTHON_ARCH: "64"
       PYTHON_ROOT: "C:\\Miniconda36-x64"
       CONDA_INSTRUMENTATION_ENABLED: "true"

     - PYTHON: "C:\\Python27_32"
       PYTHON_VERSION: "2.7"
       PYTHON_ARCH: "32"
       PYTHON_ROOT: "C:\\Miniconda"
       CONDA_INSTRUMENTATION_ENABLED: "true"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %HOME%
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - '%PYTHON_ROOT%\\Scripts\\conda install -y -c conda-canary -c defaults -c conda-forge python=%PYTHON_VERSION% pycosat conda requests ruamel_yaml pytest pytest-cov pytest-timeout mock responses pexpect pywin32'
  - "%PYTHON_ROOT%\\Scripts\\conda install -yq conda-build=3.13"
  # conda install -y -c defaults -c conda-forge pytest pytest-cov pytest-timeout mock responses pexpect xonsh
  # TODO: add xonsh for PY3 builds
  - "%PYTHON_ROOT%\\Scripts\\pip install codecov==2.0.5"
  - "%PYTHON_ROOT%\\python -m conda init cmd.exe --dev"

build: false

test_script:
  - CALL dev-init.bat
  - py.test %ADD_COV% -m "not integration and not installed" -v
  - py.test %ADD_COV% --cov-append -m "integration and not installed" -v
  - DEL /Q /F conda.egg-info
  - conda.exe build conda.recipe
  - codecov --env PYTHON_VERSION --required
  - python -m conda.common.io
